### ISSUE TITLE
New kernel on opensource Samsung.

### ISSUE THREAD

**Issue by edward0181** [RE800T/WarhammerProject_kernel_SM-A125FZ#1]
![image](https://user-images.githubusercontent.com/6586180/166467652-74777d40-997f-4dc2-84f8-0a2007a35cdb.png)

**Comment by RE800T** [comment]
> ![image](https://user-images.githubusercontent.com/6586180/166467652-74777d40-997f-4dc2-84f8-0a2007a35cdb.png)

I am no longer doing kernel development for SM-A125F
